config/routes.rb
Rails.application.routes.draw do
  resources :stocks, only: :index

  root :to => "stocks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :stocks
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :portfolio

  def self.return_profit(startdate, enddate)
    if startdate && enddate
      start_date = Date.parse(startdate)
      end_date = Date.parse(enddate)

      self.where(:date => start_date..end_date)
    else
      Stock.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @stocks = Stock.return_profit(params[:startdate], params[:enddate])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_profit.html.erb
<%= form_tag stocks_path, :method => 'get' do %>
  <div>
    <div>
      <%= date_field_tag :startdate, params[:startdate] %>
      <%= date_field_tag :enddate, params[:enddate] %>
    </div>
    <div>
      <%= submit_tag "See Profit" %>
    </div>
  </div>
<% end %>

app/views/stocks/index.html.erb
<h1>Portfolio profit - Stocks</h1>

<div>
  <%= render "partials/profit" %>
</div>

<div>
  <% result = @stocks.reduce(0) do |sum, stock| %>
    <% sum + stock.price %>
  <% end %>
  <strong>Profit: <%= result %></strong>
</div>

<div>
  <% @stocks.each do |stock| %>
    <div>
      <p>Date: <%= stock.date %></p>
      <p>Price: <%= stock.price %></p>
    </div>
  <% end %>  
</div>

app/views/stocks/profit.html.erb
<h1>Portfolio profit - Stocks</h1>
 
<div>
  <%= render "partials/profit" %>
</div>

<div>
  <% @stocks.each do |stock| %>
    <div>
      <p>Date: <%= stock.date %></p>
      <p>Price: <%= stock.price %></p>
    </div>
  <% end %>  
</div>